### ISSUE TITLE
Tracking Issue: DEX UI v2

### ISSUE THREAD

**Issue by JasonMHasperhoven** [penumbra-zone/dex-explorer#36]
# Overview

This epic focuses on upgrading Penumbra's decentralized exchange (DEX) and creating a Minimum Viable Product (MVP). This MVP will lay the groundwork for future development and provide a solid base to expand it into a full-fletched DEX that will highlight the capabilities of Penumbra.

The plan is to do it in 2 phases:

## Phase 1

In this phase, we make quality improvement to the codebase so that it's properly setup as per production standards and rearrange the existing components into 2 pages: Trade & Explorer.

The idea of this phase is to make minimal changes required so that we can get to a new, more functional layout without much effort.

The trade page will reuse the existing components (Chart, Depth Chart & Order Book) and only requires a new pair selector, while the explorer page will combine the Swaps & Blocks component into one screen, after which these components will be replaced with an updated design.

👉 [View Figma Design](https://www.figma.com/design/9wV7YYWN8DI2eJ29kOuZgi/DEX-Phase-1?node-id=0-1&t=AmbSEDrB4aWCpfU9-1)

**Tasks**
- [x] https://github.com/penumbra-zone/dex-explorer/issues/37
- [x] https://github.com/penumbra-zone/dex-explorer/issues/38
- [x] https://github.com/penumbra-zone/dex-explorer/issues/39
- [x] https://github.com/penumbra-zone/dex-explorer/issues/40

## Phase 2

For phase 2, we will build out the features required to make this into a minimal viable DEX in which people can buy/sell assets. In this phase we will use penumbra-zone's UI library to develop the necessary components. The philosophy here should still be to minimize any work so that we get to the MVP stage as quickly as possible. For example when we're developing the order form, we should only implement market orders and add limit orders etc. later on. The same applies to the other components.

###  🎨 Design [Figma Link](https://www.figma.com/design/xWsVprkEgEihweVN9isrGQ/DEX-(Incl.-UI-Lib)?node-id=3001-9&t=uOhmz1gC9jjYMUA3-1)

**Tasks**

- [x] #46
- [x] #42
- [x] #45
- [x] https://github.com/penumbra-zone/dex-explorer/issues/63
- [x] https://github.com/penumbra-zone/dex-explorer/issues/64
- [x] https://github.com/penumbra-zone/dex-explorer/issues/65
- [x] https://github.com/penumbra-zone/dex-explorer/issues/65
- [x] https://github.com/penumbra-zone/dex-explorer/issues/66
- [x] https://github.com/penumbra-zone/dex-explorer/issues/67
- [x] https://github.com/penumbra-zone/dex-explorer/issues/86
- [ ] Implement new depth chart
- [ ] Implement an order form
    - Start with market order
- [ ] Implement balances
- [ ] Implement positions
- [ ] Implement orders
- [ ] Transaction details page
- [ ] Price impact of market swap (estimate rpc?)
